#ifndef DIO_REG_H_
#define DIO_REG_H_
/* include(s) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*/
#include "CommonHeaders.h"
/* definition(s) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*/
/* PORTA */
#define PORTA_ADDR	(0x3B)
#define DDRA_ADDR	(0x3A)
#define PINA_ADDR 	(0x39)
/* PORTB */
#define PORTB_ADDR	(0x38)
#define DDRB_ADDR	(0x37)
#define PINB_ADDR 	(0x36)
/* PORTC */
#define PORTC_ADDR	(0x35)
#define DDRC_ADDR	(0x34)
#define PINC_ADDR 	(0x33)
/* PORTD */
#define PORTD_ADDR	(0x32)
#define DDRD_ADDR	(0x31)
#define PIND_ADDR 	(0x30)
/* type definition(s) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*/

/* external variable(s) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*/

/* external function prototype(s) XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*/

/*XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX*/
#endif /* DIO_REG_H_ */